# Site settings
title: Joris Muller's Blog
email: joris.muller@jom.link
description: > # this means to ignore newlines until "baseurl:"
    Another technical blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jomuller.fr" # the base hostname & protocol for your site
github_username:  jomuller

# Build settings
markdown: kramdown
