#Site settings
title: Joris Muller's Blog
email: jomuller@jom.link
description: > # this means to ignore newlines until "baseurl:"
    Another blog about data science. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.jom.link" 
github_username:  jomuller

permalink:    /:title.html
# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
extensions: [fenced_code_blocks]
highlighter: pygments
comment: true
