# Site settings
title: Joris Muller's Blog
email: jomuller@jom.link
description: > # this means to ignore newlines until "baseurl:"
    Another technical blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.jom.link" 
github_username:  jomuller

permalink:    /:year/:month/:day/:title/
# Build settings
markdown: kramdown
